# Generated by Django 3.2.7 on 2021-09-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField()),
                ('response_ms', models.IntegerField()),
                ('path', models.CharField(max_length=200)),
                ('remote_addr', models.TextField()),
                ('host', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('PATCH', 'Atualizar'), ('PUT', 'Atualizar'), ('POST', 'Cadastrar'), ('DELETE', 'Excluir'), ('GET', 'Consultar')], max_length=10)),
                ('query_params', models.TextField()),
                ('data', models.TextField()),
                ('response', models.TextField()),
                ('status_code', models.IntegerField(choices=[(100, 'Continuar'), (101, 'Mudando Protocolos'), (102, 'Processando'), (200, 'Ok'), (201, 'Criado'), (202, 'Aceito'), (203, 'Não autorizado'), (204, 'Nenhum Conteúdo'), (205, 'Resetar Conteúdo'), (206, 'Conteúdo Parcial'), (300, 'Múltipla Escolha'), (301, 'Movido Permanentemente'), (302, 'Encontrado'), (303, 'Veja outro'), (304, 'Não modificado'), (305, 'Use Proxy'), (306, 'Proxy Trocado'), (400, 'Solicitação Inválida'), (401, 'Não autorizado'), (402, 'Pagamento necessário'), (403, 'Proibido'), (404, 'Não encontrado'), (405, 'Método não permitido'), (406, 'Não aceito'), (407, 'Autenticação de Proxy Necessária'), (408, 'Tempo de solicitação esgotado'), (409, 'Conflito'), (410, 'Perdido'), (411, 'Duração necessária'), (412, 'Falha de pré-condição'), (413, 'Solicitação da entidade muito extensa'), (414, 'Solicitação de URL muito Longa'), (415, 'Tipo de mídia não suportado'), (416, 'Solicitação de faixa não satisfatória'), (417, 'Falha na expectativa'), (500, 'Erro do Servidor Interno'), (501, 'Não implementado'), (502, 'Porta de entrada ruim'), (503, 'Serviço Indisponível'), (504, 'Tempo limite da Porta de Entrada'), (505, 'Versão HTTP não suportada')], default=1)),
                ('user_id', models.IntegerField()),
                ('view', models.CharField(max_length=200)),
                ('view_method', models.CharField(max_length=200)),
                ('errors', models.TextField()),
                ('username_persistent', models.CharField(max_length=200)),
                ('response_old', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rest_framework_tracking_apirequestlog',
                'managed': False,
            },
        ),
    ]
