# Generated by Django 3.1.5 on 2021-04-08 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('prisional', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoSuspencaoVinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVinculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('delete_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('excluido', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=100)),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('usuario_edicao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updatedvinculos_tipovinculo_related', to=settings.AUTH_USER_MODEL)),
                ('usuario_exclusao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deletevinculos_tipovinculo_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoVisitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('TipoVinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinculos.tipovinculo')),
                ('interno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interno', to='cadastros.pessoa')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoa', to='cadastros.pessoa')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipopessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Visitacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
                ('data_visitacao', models.DateTimeField()),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prisional.bloco')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinculos.tipovisitacao')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinculos.vinculo')),
            ],
        ),
        migrations.CreateModel(
            name='SuspencaoVinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinculos.motivosuspencaovinculo')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinculos.vinculo')),
            ],
        ),
    ]
