# Generated by Django 3.1.5 on 2021-04-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinculo',
            name='vinculo',
        ),
    ]
