# Generated by Django 3.1.5 on 2021-05-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("movimentacao", "0007_auto_20210524_2204")]

    operations = [
        migrations.AlterField(
            model_name="pedidoinclusaomovimentacao",
            name="motivo",
            field=models.TextField(blank=True, null=True),
        )
    ]
