# Generated by Django 3.1.5 on 2021-06-28 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("movimentacao", "0012_pedidoinclusao_tipo_escolta")]

    operations = [
        migrations.AlterField(
            model_name="pedidoinclusao",
            name="cpf",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CPF inválido",
                        regex="[0-9]{3}\\.?[0-9]{3}\\.?[0-9]{3}\\-?[0-9]{2}",
                    )
                ],
            ),
        )
    ]
