# Generated by Django 3.1.5 on 2021-07-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0014_auto_20210701_1819'),
        ('movimentacao', '0014_auto_20210705_1635'),
    ]

    operations = [
    ]
