# Generated by Django 3.1.5 on 2021-07-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movimentacao", "0015_merge_20210708_1234"),
        ("movimentacao", "0015_merge_20210708_1218"),
    ]

    operations = []
