# Generated by Django 3.1.5 on 2021-07-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movimentacao", "0016_auto_20210706_1740"),
        ("movimentacao", "0015_merge_20210708_1218"),
    ]

    operations = []
