# Generated by Django 3.1.5 on 2021-07-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0017_merge_20210708_1401'),
        ('movimentacao', '0017_auto_20210709_0952'),
    ]

    operations = [
    ]
