# Generated by Django 3.1.5 on 2021-04-28 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinculos', '0002_remove_vinculo_vinculo'),
        ('social', '0001_initial'),
        ('cadastros', '0002_auto_20210412_1158'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentopessoa',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='documentopessoa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='documentopessoa',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='documentopessoa',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='documentopessoa',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='documentopessoa',
            name='usuario_cadastro',
        ),
        migrations.RemoveField(
            model_name='interno',
            name='grau_de_instrucao',
        ),
        migrations.RemoveField(
            model_name='interno',
            name='orientacao_sexual',
        ),
        migrations.RemoveField(
            model_name='interno',
            name='profissao',
        ),
        migrations.RemoveField(
            model_name='interno',
            name='raca',
        ),
        migrations.RemoveField(
            model_name='interno',
            name='religiao',
        ),
        migrations.RemoveField(
            model_name='outronome',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='outronome',
            name='usuario_cadastro',
        ),
        migrations.AlterUniqueTogether(
            name='tipopessoa',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tipopessoa',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='tipopessoa',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='tipopessoa',
            name='usuario_cadastro',
        ),
        migrations.RemoveField(
            model_name='vulgo',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='vulgo',
            name='usuario_cadastro',
        ),
        migrations.AddField(
            model_name='documentos',
            name='data_validade',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='profissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profissao_cadastros_pessoa_related', to='social.profissao'),
        ),
        migrations.DeleteModel(
            name='CaracteristicaFisica',
        ),
        migrations.DeleteModel(
            name='DocumentoPessoa',
        ),
        migrations.DeleteModel(
            name='Interno',
        ),
        migrations.DeleteModel(
            name='ModeloTipoPessoa',
        ),
        migrations.DeleteModel(
            name='OutroNome',
        ),
        migrations.DeleteModel(
            name='TipoPessoa',
        ),
        migrations.DeleteModel(
            name='Vulgo',
        ),
    ]
