# Generated by Django 3.1.5 on 2021-05-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("juridico", "0006_auto_20210511_1823")]

    operations = [
        migrations.RenameField(
            model_name="normasjuridicas",
            old_name="norma_juridica_nome",
            new_name="norma_juridica",
        ),
        migrations.RenameField(
            model_name="titulolei",
            old_name="norma_juridica_nome",
            new_name="norma_juridica",
        ),
    ]
