# Generated by Django 3.1.5 on 2021-06-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0008_auto_20210512_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normasjuridicas',
            name='descricao',
            field=models.TextField(),
        ),
    ]
