# Generated by Django 3.1.5 on 2021-04-08 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("sigla", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("sigla", models.CharField(max_length=3)),
                (
                    "pais",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="localizacao.pais",
                    ),
                ),
            ],
            options={"unique_together": {("pais", "nome")}},
        ),
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="localizacao.estado",
                    ),
                ),
            ],
            options={"unique_together": {("estado", "nome")}},
        ),
    ]
