# Generated by Django 3.1.5 on 2021-07-06 20:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movimentacao", "0016_auto_20210706_1740"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pessoas", "0016_auto_20210702_1444"),
    ]

    operations = [
        migrations.CreateModel(
            name="Escoltas",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "delete_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("excluido", models.BooleanField(default=False)),
                (
                    "nome_missao",
                    models.CharField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
                (
                    "numero_sei",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Nº SEI inválido",
                                regex="\\d{5}\\.\\d{6}\\/\\d{4}\\-\\d{2}",
                            )
                        ],
                    ),
                ),
                ("numero_documento_sei", models.CharField(max_length=10)),
                ("ordem_missao", models.CharField(max_length=50)),
                (
                    "responsavel",
                    models.CharField(
                        choices=[("DEPEN", "DEPEN"), ("ESTADO", "ESTADO")],
                        max_length=20,
                    ),
                ),
                (
                    "data_inicio_aerea",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "hora_inicio_aerea",
                    models.TimeField(blank=True, default=None, null=True),
                ),
                (
                    "data_fim_aerea",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "hora_fim_aerea",
                    models.TimeField(blank=True, default=None, null=True),
                ),
                (
                    "descricao_aerea",
                    models.TextField(
                        blank=True, default=None, max_length=500, null=True
                    ),
                ),
                (
                    "data_inicio_terrestre",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "hora_inicio_terrestre",
                    models.TimeField(blank=True, default=None, null=True),
                ),
                (
                    "data_fim_terrestre",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "hora_fim_terrestre",
                    models.TimeField(blank=True, default=None, null=True),
                ),
                (
                    "descricao_terrestre",
                    models.TextField(
                        blank=True, default=None, max_length=500, null=True
                    ),
                ),
                (
                    "tipo_aeronave",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMERCIAL", "Comercial"),
                            ("INSTITUCIONAL", "Institucional"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "instituicao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FAB", "Força Aérea Brasileira"),
                            ("PF", "Polícia Federal"),
                            ("PRF", "Polícia Rodoviária Federal"),
                            ("PC", "Polícia Civil"),
                            ("OUTROS", "Outros"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "motivo_inativacao",
                    models.TextField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "data_ativacao",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "data_inativacao",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "pedidos_inclusao",
                    models.ManyToManyField(
                        related_name="pedido_inclusao_related",
                        to="movimentacao.PedidoInclusao",
                    ),
                ),
                (
                    "servidores_escolta_aerea",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="servidores_escolta_aerea_related",
                        to="pessoas.Servidor",
                    ),
                ),
                (
                    "servidores_escolta_terrestre",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="servidores_escolta_terrestre_related",
                        to="pessoas.Servidor",
                    ),
                ),
                (
                    "usuario_ativacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ativacao_escolta_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_cadastro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_edicao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updatedescolta_escoltas_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_exclusao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deleteescolta_escoltas_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_inativacao",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inativacao_escolta_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
