# Generated by Django 3.1.5 on 2021-04-30 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("pessoas", "0005_sinaisparticulares_motivo_ativacao")]

    operations = [
        migrations.AlterModelOptions(name="vulgo", options={}),
        migrations.RemoveField(model_name="vulgo", name="interno"),
        migrations.AlterOrderWithRespectTo(name="interno", order_with_respect_to="id"),
        migrations.CreateModel(
            name="InternoVulgosThroughModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "interno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pessoas.interno",
                    ),
                ),
                (
                    "vulgo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pessoas.vulgo"
                    ),
                ),
            ],
            options={"ordering": ("order",), "abstract": False},
        ),
        migrations.AddField(
            model_name="interno",
            name="vulgo",
            field=models.ManyToManyField(
                through="pessoas.InternoVulgosThroughModel", to="pessoas.Vulgo"
            ),
        ),
    ]
