# Generated by Django 3.1.5 on 2021-05-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_auto_20210428_1656"),
        ("pessoas", "0006_auto_20210430_1854"),
    ]

    operations = [
        migrations.AlterModelOptions(name="vulgo", options={"ordering": ["nome"]}),
        migrations.AlterField(
            model_name="interno",
            name="documentos",
            field=models.ManyToManyField(blank=True, to="cadastros.Documentos"),
        ),
    ]
