# Generated by Django 3.1.5 on 2021-06-09 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0001_initial'),
        ('pessoas', '0010_advogado_emailadvogado_oab_rgadvogado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='naturalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='naturalidade_advogado_pessoas_advogado_related', to='localizacao.cidade'),
        ),
    ]
