# Generated by Django 3.1.5 on 2021-06-09 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("localizacao", "0001_initial"),
        ("pessoas", "0011_auto_20210609_1720"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advogado",
            name="estado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="estado_advogado_pessoas_advogado_related",
                to="localizacao.estado",
            ),
        )
    ]
