# Generated by Django 3.1.5 on 2021-07-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0019_visitante_documentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rgvisitante',
            name='orgao_expedidor',
        ),
        migrations.RemoveField(
            model_name='rgvisitante',
            name='usuario_cadastro',
        ),
        migrations.RemoveField(
            model_name='rgvisitante',
            name='usuario_edicao',
        ),
        migrations.RemoveField(
            model_name='rgvisitante',
            name='usuario_exclusao',
        ),
        migrations.RemoveField(
            model_name='rgvisitante',
            name='visitante',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='documentos',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='enderecos',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='grau_instrucao',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='naturalidade',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='necessidade_especial',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='orientacao_sexual',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='profissao',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='raca',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='religiao',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='telefones',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='usuario_cadastro',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='usuario_edicao',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='usuario_exclusao',
        ),
        migrations.DeleteModel(
            name='EmailVisitante',
        ),
        migrations.DeleteModel(
            name='RgVisitante',
        ),
        migrations.DeleteModel(
            name='Visitante',
        ),
    ]
