# Generated by Django 3.1.5 on 2021-07-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0002_anuencia_documentoanuencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuencia',
            name='declaracao',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='documento_anuencia_related', to='visitante.documentoanuencia'),
        ),
    ]
