# Generated by Django 3.1.5 on 2021-07-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0003_auto_20210728_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuencia',
            options={'verbose_name': 'Anuencia', 'verbose_name_plural': 'Anuencia'},
        ),
        migrations.RemoveField(
            model_name='anuencia',
            name='declaracao',
        ),
        migrations.AddField(
            model_name='anuencia',
            name='arquivo',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='anuencia',
            name='arquivo_temp',
            field=models.FileField(default='', upload_to='documento_anuencia'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DocumentoAnuencia',
        ),
    ]
