# Generated by Django 3.1.5 on 2021-08-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("visitante", "0007_auto_20210803_1148")]

    operations = [
        migrations.AlterField(
            model_name="visitantemovimentacao",
            name="data_contato",
            field=models.DateField(blank=True, default=None, null=True),
        )
    ]
