# Generated by Django 3.1.5 on 2021-08-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0008_auto_20210803_1513'),
        ('visitante', '0006_auto_20210803_1612'),
    ]

    operations = [
    ]
