# Generated by Django 3.1.5 on 2021-08-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("visitante", "0010_auto_20210803_1709")]

    operations = [
        migrations.RenameField(
            model_name="visitantemovimentacao", old_name="situacao", new_name="fase"
        )
    ]
