# Generated by Django 3.1.5 on 2021-08-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0011_auto_20210803_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='data_validade',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='situacao',
            field=models.BooleanField(default=False),
        ),
    ]
