# Generated by Django 3.1.5 on 2021-08-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("visitante", "0016_auto_20210806_1654")]

    operations = [
        migrations.AlterField(
            model_name="documentosvisitante",
            name="arquivo_temp",
            field=models.FileField(upload_to="documentos_visitante"),
        )
    ]
