# Generated by Django 3.1.5 on 2021-08-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0020_auto_20210823_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosvisitante',
            name='filename',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
